version: '3.1'

services:
  springboot:
    build: .
    image: iquee/spring-geo-mongo:latest
    container_name: spring-compose
    ports:
      - 9000:9000
    working_dir: /opt/app
    networks:
      - xyz
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo-compose
    networks:
      - xyz
    ports:  
      - 27017:27017
    volumes:
      - $HOME/docker/spring-geo-mongo/mongodb:/data/db
    
networks:
  xyz: